apiVersion: v1
kind: Secret
metadata:
  name: discord
type: Opaque
stringData:
  token: <discord-token>
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql
type: Opaque
stringData:
  user: <User>
  password: <Password>
  base: <BaseKey>
